-- 코드를 작성해주세요
WITH RECURSIVE ECOLI_GEN AS (
    SELECT ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT A.ID, B.GEN +1
    FROM ECOLI_DATA A
    JOIN ECOLI_GEN B ON A.PARENT_ID = B.ID
)

SELECT ID
FROM ECOLI_GEN
WHERE GEN=3
ORDER BY ID