-- 코드를 작성해주세요
WITH RECURSIVE ECOLI_TREE AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT A.ID, B.GENERATION + 1
    FROM ECOLI_DATA A
    JOIN ECOLI_TREE B ON A.PARENT_ID = B.ID
)

SELECT ID
FROM ECOLI_TREE
WHERE GENERATION = 3