-- 코드를 작성해주세요
WITH PARENT_ECOLI AS (
    SELECT A.ID, A.PARENT_ID
    FROM ECOLI_DATA A JOIN ECOLI_DATA B
    ON A.PARENT_ID = B.ID
)

SELECT A.ID
FROM ECOLI_DATA A JOIN PARENT_ECOLI B
ON A.PARENT_ID = B.ID
WHERE A.PARENT_ID 
NOT IN(
    SELECT C.ID
    FROM ECOLI_DATA C JOIN PARENT_ECOLI D
    ON C.PARENT_ID = D.ID
)
ORDER BY A.ID;