-- 자식의 개수를 구하는법, PARENT_ID가 동일한 개체의 개수를 센다
-- ID가 PARENT_ID랑 동일한 개수
SELECT A.ID, COUNT(B.ID) AS CHILD_COUNT
FROM ECOLI_DATA A 
LEFT JOIN ECOLI_DATA B
ON A.ID = B.PARENT_ID
GROUP BY A.ID
ORDER BY A.ID;