-- 코드를 작성해주세요
WITH ECOLI_TITLE AS (
    SELECT 
        NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) SIZE,
        ID
    FROM ECOLI_DATA
)

SELECT 
    ID,
    CASE SIZE
        WHEN 1 THEN 'CRITICAL'
        WHEN 2 THEN 'HIGH'
        WHEN 3 THEN 'MEDIUM'
        ELSE 'LOW'
        END AS COLONY_NAME
FROM ECOLI_TITLE
ORDER BY ID