-- 코드를 작성해주세요
WITH ECOLI_TITLES AS (
    SELECT 
        ID,
    NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS TITLE_NUM
    FROM ECOLI_DATA
)


SELECT ID,
CASE
    WHEN TITLE_NUM = 1 THEN 'CRITICAL'
    WHEN TITLE_NUM = 2 THEN 'HIGH'
    WHEN TITLE_NUM = 3 THEN 'MEDIUM'
    WHEN TITLE_NUM = 4 THEN 'LOW'
END AS COLONY_NAME
FROM ECOLI_TITLES
ORDER BY ID;
    
    
