-- 코드를 작성해주세요
WITH ECOLI_TITLE AS (
SELECT ID, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS SIZE
FROM ECOLI_DATA
)

SELECT ID,
CASE SIZE
    WHEN 1 THEN 'CRITICAL'
    WHEN 2 THEN 'HIGH'
    WHEN 3 THEN 'MEDIUM'
    WHEN 4 THEN 'LOW'
    END AS COLONY_NAME
FROM ECOLI_TITLE
ORDER BY ID;