-- 코드를 입력하세요
WITH BUSY_CAR_LIST AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN DATE_FORMAT(START_DATE, '%Y-%m-%d') AND DATE_FORMAT(END_DATE, '%Y-%m-%d')
)

SELECT DISTINCT CAR_ID, '대여 가능' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID NOT IN (SELECT CAR_ID FROM BUSY_CAR_LIST)

UNION

SELECT CAR_ID, '대여중' AS AVAILABILITY
FROM BUSY_CAR_LIST

ORDER BY CAR_ID DESC