-- 코드를 작성해주세요
SELECT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS A
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME ="C#")
OR  SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME ="Python")
ORDER BY A.ID;