-- 코드를 작성해주세요
WITH FISH_RNK AS (
SELECT
    RANK() OVER(PARTITION BY A.FISH_TYPE ORDER BY A.LENGTH DESC) RNK,
    A.ID,
    B.FISH_NAME,
    A.LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
)

SELECT ID, FISH_NAME, LENGTH
FROM FISH_RNK
WHERE RNK = 1
ORDER BY ID
