-- 코드를 작성해주세요
SELECT INFO.ID, NAME_INFO.FISH_NAME , INFO.LENGTH
FROM FISH_INFO INFO 
JOIN FISH_NAME_INFO NAME_INFO ON INFO.FISH_TYPE = NAME_INFO.FISH_TYPE
WHERE (INFO.FISH_TYPE, INFO.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY INFO.ID;